# fly.toml app configuration file generated for ofeks-network on 2023-12-04T18:59:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ofeks-network"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
